/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ycallec.gestform.model;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import org.ycallec.gestform.dao.FormationDAO;
import org.ycallec.gestform.dao.StagiaireDAO;

/**
 *
 * @author callec
 */
public class Fen extends javax.swing.JFrame {

    FormationTableModel ftm;
    StagiaireTableModel stm;
    StagiaireTableModel stmf;

    /**
     * Creates new form Fen
     */
    public Fen() {
        initComponents();

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        formationTable.getColumnModel().getColumn(0).setCellRenderer(rightRenderer);

        List<Formation> formations = FormationDAO.findAllFormation();
        for (Formation f : formations) {
            StagiaireComboBoxFormation.addItem(f);
        }

        panelFormDetails.setVisible(false);
        panelSuppForm.setVisible(false);
        
        formationTable.setSelectionModel(new DefaultListSelectionModel() {
    private static final long serialVersionUID = 1L;

    boolean gestureStarted = false;

    @Override
    public void setSelectionInterval(int index0, int index1) {
        if(!gestureStarted){
            if (isSelectedIndex(index0)) {
                super.removeSelectionInterval(index0, index1);
            } else {
                super.addSelectionInterval(index0, index1);
            }
        }
        gestureStarted = true;
    }

    @Override
    public void setValueIsAdjusting(boolean isAdjusting) {
        if (isAdjusting == false) {
            gestureStarted = false;
        }
    }

});
        
        formationTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent evt) {
                int index = formationTable.getSelectedRow(); // On récupère le numéro de la ligne sélectionnée
                if (index > -1) {
                    Formation form = ftm.getFormation(index); //On récupère la formation en fonction du numéro de ligne dans le model
                    panelFormDetails.setVisible(true);
                    List<Stagiaire> listeStagiaire = StagiaireDAO.findBy(form);
                    stmf.setStagiaires(listeStagiaire);
                    stmf.fireTableDataChanged();
                    panelSuppForm.setVisible(true);

                } else {
                    stmf.clearStagiaire();
                    panelFormDetails.setVisible(false);
                    panelSuppForm.setVisible(false);
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        FormationPanel = new javax.swing.JPanel();
        FormationAddPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FormationTextField = new javax.swing.JTextField();
        FormationAddButton = new javax.swing.JButton();
        FormationListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formationTable = new javax.swing.JTable();
        FormationTableLabel = new javax.swing.JLabel();
        panelFormDetails = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        panelSuppForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FormationSuppButton = new javax.swing.JButton();
        StagiairePanel = new javax.swing.JPanel();
        StagiaireListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StagiaireTableList = new javax.swing.JTable();
        StagiaireListLabel = new javax.swing.JLabel();
        StagiaireAddPanel = new javax.swing.JPanel();
        StagiaireAddLabel = new javax.swing.JLabel();
        StagiaireAddButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NomStagiaireTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PrenomStagiaireTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MatriculeStagiaireTextField = new javax.swing.JTextField();
        StagiaireComboBoxFormation = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormationAddPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ajout de formation");

        FormationTextField.setText("Nom de la formation");
        FormationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationTextFieldActionPerformed(evt);
            }
        });

        FormationAddButton.setText("OK");
        FormationAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormationAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FormationAddPanelLayout = new javax.swing.GroupLayout(FormationAddPanel);
        FormationAddPanel.setLayout(FormationAddPanelLayout);
        FormationAddPanelLayout.setHorizontalGroup(
            FormationAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormationAddPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormationAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormationAddPanelLayout.createSequentialGroup()
                        .addComponent(FormationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FormationAddButton)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormationAddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89))))
        );
        FormationAddPanelLayout.setVerticalGroup(
            FormationAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormationAddPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(FormationAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormationAddButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        FormationTextField.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                FormationTextField.setText("");
            }
        });

        FormationListPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, null));

        formationTable.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        formationTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(formationTable);
        ftm = new FormationTableModel(FormationDAO.findAllFormation());
        formationTable.setModel(ftm);

        FormationTableLabel.setText("Liste des formations");

        javax.swing.GroupLayout FormationListPanelLayout = new javax.swing.GroupLayout(FormationListPanel);
        FormationListPanel.setLayout(FormationListPanelLayout);
        FormationListPanelLayout.setHorizontalGroup(
            FormationListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormationListPanelLayout.createSequentialGroup()
                .addGroup(FormationListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormationListPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormationListPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(FormationTableLabel)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        FormationListPanelLayout.setVerticalGroup(
            FormationListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormationListPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(FormationTableLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        stmf = new StagiaireTableModel();
        jTable1.setModel(stmf);
        jTable1.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        jLabel2.setText("Stagiaires de la formation");

        javax.swing.GroupLayout panelFormDetailsLayout = new javax.swing.GroupLayout(panelFormDetails);
        panelFormDetails.setLayout(panelFormDetailsLayout);
        panelFormDetailsLayout.setHorizontalGroup(
            panelFormDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormDetailsLayout.createSequentialGroup()
                .addGroup(panelFormDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormDetailsLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormDetailsLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelFormDetailsLayout.setVerticalGroup(
            panelFormDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormDetailsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        panelSuppForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Supprimer la formation");

        FormationSuppButton.setText("OK");

        javax.swing.GroupLayout panelSuppFormLayout = new javax.swing.GroupLayout(panelSuppForm);
        panelSuppForm.setLayout(panelSuppFormLayout);
        panelSuppFormLayout.setHorizontalGroup(
            panelSuppFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuppFormLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(FormationSuppButton)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        panelSuppFormLayout.setVerticalGroup(
            panelSuppFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuppFormLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelSuppFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormationSuppButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FormationPanelLayout = new javax.swing.GroupLayout(FormationPanel);
        FormationPanel.setLayout(FormationPanelLayout);
        FormationPanelLayout.setHorizontalGroup(
            FormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormationPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(FormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSuppForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FormationAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FormationListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(panelFormDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        FormationPanelLayout.setVerticalGroup(
            FormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormationPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(FormationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFormDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormationPanelLayout.createSequentialGroup()
                        .addComponent(FormationListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FormationAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(panelSuppForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Formation", FormationPanel);

        StagiaireListPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(StagiaireTableList);
        stm = new StagiaireTableModel(StagiaireDAO.findAllStagiaire());
        StagiaireTableList.setModel(stm);

        StagiaireListLabel.setText("Liste des stagiaires");

        javax.swing.GroupLayout StagiaireListPanelLayout = new javax.swing.GroupLayout(StagiaireListPanel);
        StagiaireListPanel.setLayout(StagiaireListPanelLayout);
        StagiaireListPanelLayout.setHorizontalGroup(
            StagiaireListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StagiaireListPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(StagiaireListPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(StagiaireListLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StagiaireListPanelLayout.setVerticalGroup(
            StagiaireListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StagiaireListPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(StagiaireListLabel)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        StagiaireAddPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        StagiaireAddLabel.setText("Ajout de stagiaire");

        StagiaireAddButton.setText("OK");
        StagiaireAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StagiaireAddButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Nom ");

        jLabel6.setText("Prénom");

        jLabel7.setText("Matricule");

        StagiaireComboBoxFormation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StagiaireComboBoxFormationActionPerformed(evt);
            }
        });

        jLabel8.setText("Formation");

        javax.swing.GroupLayout StagiaireAddPanelLayout = new javax.swing.GroupLayout(StagiaireAddPanel);
        StagiaireAddPanel.setLayout(StagiaireAddPanelLayout);
        StagiaireAddPanelLayout.setHorizontalGroup(
            StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StagiaireAddLabel)
                .addGap(127, 127, 127))
            .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                        .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NomStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StagiaireAddButton)
                                    .addComponent(PrenomStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MatriculeStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StagiaireAddPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StagiaireComboBoxFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                        .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        StagiaireAddPanelLayout.setVerticalGroup(
            StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StagiaireAddPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(StagiaireAddLabel)
                .addGap(28, 28, 28)
                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NomStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PrenomStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MatriculeStagiaireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(StagiaireAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(StagiaireComboBoxFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(StagiaireAddButton)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout StagiairePanelLayout = new javax.swing.GroupLayout(StagiairePanel);
        StagiairePanel.setLayout(StagiairePanelLayout);
        StagiairePanelLayout.setHorizontalGroup(
            StagiairePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StagiairePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(StagiaireListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(StagiaireAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        StagiairePanelLayout.setVerticalGroup(
            StagiairePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StagiairePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(StagiairePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StagiaireListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StagiaireAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Stagiaire", StagiairePanel);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("Formation");
        jTabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StagiaireAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StagiaireAddButtonActionPerformed
        String nomStagiaire = NomStagiaireTextField.getText();
        String prenomStagiaire = PrenomStagiaireTextField.getText();
        String strMatricule = MatriculeStagiaireTextField.getText();
        int matricule = Integer.parseInt(strMatricule);

        Object obj = StagiaireComboBoxFormation.getSelectedItem();

        Formation formation = (Formation) obj;

        try {
            Stagiaire newFormStagiaire = new Stagiaire(nomStagiaire, prenomStagiaire, 1, matricule, formation);
            StagiaireDAO.saveStagiaire(newFormStagiaire);
            stm.addStagiaire(newFormStagiaire);
            stm.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
        }
        NomStagiaireTextField.setText(null);
        PrenomStagiaireTextField.setText(null);
        MatriculeStagiaireTextField.setText(null);

    }//GEN-LAST:event_StagiaireAddButtonActionPerformed

    private void FormationAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationAddButtonActionPerformed
        String nomFormation = FormationTextField.getText();
        try {
            Formation newForm = new Formation(0, nomFormation);
            FormationDAO.saveFormation(newForm);
            ftm.addFormation(newForm);
            ftm.fireTableDataChanged();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        FormationTextField.setText(null);
    }//GEN-LAST:event_FormationAddButtonActionPerformed


    private void FormationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormationTextFieldActionPerformed

    private void StagiaireComboBoxFormationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StagiaireComboBoxFormationActionPerformed

    }//GEN-LAST:event_StagiaireComboBoxFormationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FormationAddButton;
    private javax.swing.JPanel FormationAddPanel;
    private javax.swing.JPanel FormationListPanel;
    private javax.swing.JPanel FormationPanel;
    private javax.swing.JButton FormationSuppButton;
    private javax.swing.JLabel FormationTableLabel;
    private javax.swing.JTextField FormationTextField;
    private javax.swing.JTextField MatriculeStagiaireTextField;
    private javax.swing.JTextField NomStagiaireTextField;
    private javax.swing.JTextField PrenomStagiaireTextField;
    private javax.swing.JButton StagiaireAddButton;
    private javax.swing.JLabel StagiaireAddLabel;
    private javax.swing.JPanel StagiaireAddPanel;
    private javax.swing.JComboBox<Formation> StagiaireComboBoxFormation;
    private javax.swing.JLabel StagiaireListLabel;
    private javax.swing.JPanel StagiaireListPanel;
    private javax.swing.JPanel StagiairePanel;
    private javax.swing.JTable StagiaireTableList;
    private javax.swing.JTable formationTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelFormDetails;
    private javax.swing.JPanel panelSuppForm;
    // End of variables declaration//GEN-END:variables

}
